### ISSUE TITLE
Consider parameterized structs

### ISSUE THREAD

**Issue by jlapeyre** [Marco-Di-Tullio/Fermionic.jl#5]
You might find it convenient to use:
```julia
struct State{T}
    st::Array{T,1}
    ope::Op
end
```
rather than having hardcoded real and complex types. (Note also that you don' need a trailing `;` after the definition.

**Comment by Marco-Di-Tullio** [comment]
Thank you for the advice. I am aware that defining Real and Complex types is both unnecesary and confussing. It is one of the major upgrades I am planning. It requires a lot of changes, so it must be done with caution. I will open a new branch and start working on it, using your suggestion.

**Comment by Marco-Di-Tullio** [comment]
I just made the changes you suggested. It looks much cleaner know. Thank you for the suggestion!

**Comment by Marco-Di-Tullio** [comment]
I will try to do the same with State and State Sparse, altough I think it is more complicated

**Comment by jlapeyre** [comment]
You can try something like this:
```julia
using SparseArrays

struct Op
    n::Int
end

struct State{T<:AbstractVector}
    st::T
    ope::Op
end
```

```julia
julia> st1 = State(spzeros(3), Op(4))
State{SparseVector{Float64, Int64}}(3-element SparseVector{Float64, Int64} with 0 stored entries, Op(4))

julia> st2 = State(zeros(3), Op(4))
State{Vector{Float64}}([0.0, 0.0, 0.0], Op(4))

julia> st3 = State(zeros(Complex{Float64},3), Op(4))
State{Vector{ComplexF64}}(ComplexF64[0.0 + 0.0im, 0.0 + 0.0im, 0.0 + 0.0im], Op(4))
```

There are several packages that have some ideas about this. For example FillArrays.jl

**Comment by Marco-Di-Tullio** [comment]
Just done this as well. Much appreciate your advice!  :)
I will finally try to remove the necessity for a State_fixed struct, but this case is a little bit different, as I would need to add an optional argument in the construction of the Struct and make bigger changes to some methods.

**Comment by Marco-Di-Tullio** [comment]
I was able to build the whole program with just a single Struct for State. I fusioned State and State_fixed with a mutable struct like this:

```julia
mutable struct State{T<:AbstractVector}
    st::T
    ope::Op
    nume::Union{Int64,Missing}
end

function State(st,ope;nume=missing)
    return State(st,ope,nume)
end
```

Once again, thanks for remarking this issue. I will rewrite the examples in the following days. Hopefully the package is much clearer now.

**Comment by jlapeyre** [comment]
Great to hear. The last fusion is not as clear of an advantage as the others.  When you go from immutable to mutable, you lose some safety and lose some chances for the compiler to optimize behind the scenes. But, sometimes the flexibility is worth it.

**Comment by Marco-Di-Tullio** [comment]
I didn't know about that. I will look into these problems and see wheter or not to use mutable structs. 
This is my first project with Julia, so I find really helpful all your feedback!

**Comment by Marco-Di-Tullio** [comment]
I ended up going back to unmutable structs.  Once again, really appreciate your advice. 
I will close this issue now.
